from oscillo import *
root = Tk()
root.iconbitmap("skander.ico")
root.title(" -- Test de Rotation")
g1 = OscilloGraphe()
g1.pack()
g2 = OscilloGraphe(300,500)
g2.pack()
g2.traceCourbe()
g3 = OscilloGraphe(600,400)
g3.configure(bg = 'red')
g3.pack(padx = 5, pady = 5)
g3.traceCourbe(phase = 1.75, coul = 'white')
g3.traceCourbe(phase = 3.24, coul = 'white')
g3.traceCourbe(phase = 2.22, coul = 'white')
g3.traceCourbe(phase = 0.57, coul = 'white')
g4 = OscilloGraphe()
g4.pack()
